apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: first-app
    helm:
      parameters:
      - name: pvc.storage_class
        value: nfs-client
    repoURL: https://vitaliget.github.io/helm-23-23/
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
